export type NodeCategory =
  | 'concept'
  | 'progressive-mp4'
  | 'fragmented-mp4'
  | 'streaming'
  | 'box'
  | 'timing'
  | 'sample-table'

export type Node = {
  id: string
  label: string
  category: NodeCategory
  description: string
  whyItMatters: string
}

export type Edge = {
  source: string
  target: string
  label: string
  description: string
}

export const nodes: Node[] = [
  {
    id: 'mp4-file',
    label: 'MP4 File',
    category: 'concept',
    description: 'An ISO Base Media File Format container for timed media such as audio and video.',
    whyItMatters: 'It is the top-level mental model: bytes are organized into boxes that describe and carry samples.',
  },
  {
    id: 'progressive-mp4',
    label: 'Progressive MP4',
    category: 'progressive-mp4',
    description: 'A self-contained MP4 commonly downloaded or played from a single URL.',
    whyItMatters: 'Players can start once enough metadata and media bytes are available, especially when moov is near the front.',
  },
  {
    id: 'fragmented-mp4',
    label: 'Fragmented MP4 / fMP4',
    category: 'fragmented-mp4',
    description: 'An MP4 organized as initialization metadata followed by media fragments.',
    whyItMatters: 'This is the common structure used by modern adaptive streaming pipelines such as DASH and HLS fMP4.',
  },
  {
    id: 'init-segment',
    label: 'Init Segment',
    category: 'fragmented-mp4',
    description: 'The startup segment that carries file type and global track metadata.',
    whyItMatters: 'A player needs it before decoding media segments because it declares codecs, tracks, and timescales.',
  },
  {
    id: 'media-segment',
    label: 'Media Segment',
    category: 'fragmented-mp4',
    description: 'A streamable chunk containing metadata and media bytes for a time range.',
    whyItMatters: 'ABR playback fetches media segment by segment, allowing buffering and quality switching.',
  },
  {
    id: 'media-fragment',
    label: 'Media Fragment',
    category: 'fragmented-mp4',
    description: 'The container-level fragment structure, usually represented by moof plus mdat.',
    whyItMatters: 'It is the ISOBMFF mechanism that makes independent segment metadata possible.',
  },
  {
    id: 'abr',
    label: 'ABR',
    category: 'streaming',
    description: 'Adaptive Bitrate streaming: switching quality levels based on bandwidth and buffer health.',
    whyItMatters: 'ABR keeps playback smooth while selecting the best sustainable representation.',
  },
  {
    id: 'manifest',
    label: 'Manifest',
    category: 'streaming',
    description: 'A playlist or MPD describing available media, segments, timing, and variants.',
    whyItMatters: 'The player uses it as the map for choosing init segments, media segments, and representations.',
  },
  {
    id: 'representation',
    label: 'Representation',
    category: 'streaming',
    description: 'One encoded version of the same content, such as a specific bitrate, resolution, or codec.',
    whyItMatters: 'ABR switches among representations when they are time-aligned and compatible.',
  },
  {
    id: 'ftyp',
    label: 'ftyp',
    category: 'box',
    description: 'File Type Box. Declares brands and compatibility for the file.',
    whyItMatters: 'It helps demuxers identify the kind of ISOBMFF file and supported feature set.',
  },
  {
    id: 'styp',
    label: 'styp',
    category: 'box',
    description: 'Segment Type Box. Declares brands and compatibility for an individual media segment.',
    whyItMatters: 'It lets segmented media advertise the ISOBMFF feature set used by that segment, similar to ftyp for a whole file or init segment.',
  },
  {
    id: 'moov',
    label: 'moov',
    category: 'box',
    description: 'Movie Box. Contains global metadata for the MP4 presentation.',
    whyItMatters: 'Players use it to understand tracks, timing, codecs, and sample tables.',
  },
  {
    id: 'mvex',
    label: 'mvex',
    category: 'box',
    description: 'Movie Extends Box. Signals that the movie uses fragments and provides defaults for them.',
    whyItMatters: 'Fragmented MP4 readers use mvex to know that sample metadata continues in later moof boxes.',
  },
  {
    id: 'trex',
    label: 'trex',
    category: 'box',
    description: 'Track Extends Box. Stores default sample description, duration, size, and flags for one fragmented track.',
    whyItMatters: 'It reduces repetition because tfhd and trun boxes can inherit defaults from trex.',
  },
  {
    id: 'mvhd',
    label: 'mvhd',
    category: 'box',
    description: 'Movie Header Box. Defines movie-level timing, duration, and presentation defaults.',
    whyItMatters: 'It gives the player global timeline context before individual tracks add their own details.',
  },
  {
    id: 'trak',
    label: 'trak',
    category: 'box',
    description: 'Track Box. Describes one media track, such as video, audio, or subtitles.',
    whyItMatters: 'Track metadata tells the player how each stream is identified and interpreted.',
  },
  {
    id: 'tkhd',
    label: 'tkhd',
    category: 'box',
    description: 'Track Header Box. Stores track identity, enabled state, duration, layer, volume, and display dimensions.',
    whyItMatters: 'It tells a player the basic properties of a track before deeper media metadata is read.',
  },
  {
    id: 'mdia',
    label: 'mdia',
    category: 'box',
    description: 'Media Box. Contains media-specific information for a track.',
    whyItMatters: 'It groups timing, handler, and media information needed to decode a track.',
  },
  {
    id: 'minf',
    label: 'minf',
    category: 'box',
    description: 'Media Information Box. Carries media handler-specific information.',
    whyItMatters: 'It leads to the sample table, where samples are mapped to time and byte locations.',
  },
  {
    id: 'stbl',
    label: 'stbl',
    category: 'sample-table',
    description: 'Sample Table Box. Indexes samples in a progressive MP4 track.',
    whyItMatters: 'It is the core lookup structure for sample timing, sizes, keyframes, and offsets.',
  },
  {
    id: 'stsd',
    label: 'stsd',
    category: 'sample-table',
    description: 'Sample Description Box. Describes codec configuration and sample entry details.',
    whyItMatters: 'Decoders need this information to initialize correctly.',
  },
  {
    id: 'av1c',
    label: 'av1C',
    category: 'box',
    description: 'AV1 Codec Configuration Box. Carries AV1 decoder configuration records for AV1 sample entries.',
    whyItMatters: 'A decoder needs this compact codec setup data before it can interpret AV1 samples.',
  },
  {
    id: 'avcc',
    label: 'avcC',
    category: 'box',
    description: 'AVC Configuration Box. Carries H.264/AVC decoder configuration such as SPS and PPS parameter sets.',
    whyItMatters: 'Without avcC, a decoder may not know profile, level, NAL length size, or parameter sets needed for H.264 samples.',
  },
  {
    id: 'hvcc',
    label: 'hvcC',
    category: 'box',
    description: 'HEVC Configuration Box. Carries H.265/HEVC decoder configuration such as VPS, SPS, and PPS arrays.',
    whyItMatters: 'It initializes HEVC decoding and describes how encoded NAL units should be interpreted.',
  },
  {
    id: 'esds',
    label: 'esds',
    category: 'box',
    description: 'Elementary Stream Descriptor Box. Carries MPEG-4 elementary stream and decoder configuration descriptors, commonly for AAC.',
    whyItMatters: 'It gives audio/video decoders the codec-specific setup needed to parse elementary stream samples.',
  },
  {
    id: 'stts',
    label: 'stts',
    category: 'timing',
    description: 'Decoding Time to Sample Box. Maps samples to decode durations.',
    whyItMatters: 'It builds the decode timeline for progressive MP4 playback.',
  },
  {
    id: 'stss',
    label: 'stss',
    category: 'sample-table',
    description: 'Sync Sample Box. Lists random-access samples, usually keyframes.',
    whyItMatters: 'Seeking and segment boundaries generally need sync samples.',
  },
  {
    id: 'stsz',
    label: 'stsz',
    category: 'sample-table',
    description: 'Sample Size Box. Lists the size of each sample or a constant sample size.',
    whyItMatters: 'The demuxer uses it to know how many bytes to read for each sample.',
  },
  {
    id: 'stco-co64',
    label: 'stco/co64',
    category: 'sample-table',
    description: 'Chunk Offset Boxes. Point from sample table chunks to byte offsets in mdat.',
    whyItMatters: 'They connect metadata to the actual media payload locations.',
  },
  {
    id: 'mdat',
    label: 'mdat',
    category: 'box',
    description: 'Media Data Box. Contains encoded audio, video, or subtitle bytes.',
    whyItMatters: 'This is the payload the decoder ultimately consumes after metadata explains how to parse it.',
  },
  {
    id: 'sidx',
    label: 'sidx',
    category: 'box',
    description: 'Segment Index Box. Optional index metadata that can describe subsegment timing, sizes, and references.',
    whyItMatters: 'It can help clients locate segment ranges, but DASH fMP4 media segments do not always include it.',
  },
  {
    id: 'moof',
    label: 'moof',
    category: 'fragmented-mp4',
    description: 'Movie Fragment Box. Contains metadata for one media fragment.',
    whyItMatters: 'In fMP4 streaming, each media segment needs moof metadata so the player can interpret the mdat bytes.',
  },
  {
    id: 'mfra',
    label: 'mfra',
    category: 'box',
    description: 'Movie Fragment Random Access Box. Optional top-level index for finding random-access points in movie fragments.',
    whyItMatters: 'It lets players seek into fragmented files by mapping presentation times to fragment byte offsets instead of scanning every moof.',
  },
  {
    id: 'tfra',
    label: 'tfra',
    category: 'box',
    description: 'Track Fragment Random Access Box. Lists random-access times and fragment byte offsets for a track.',
    whyItMatters: 'It gives seek/index readers a compact map from track time to the moof that contains a random-access point.',
  },
  {
    id: 'mfro',
    label: 'mfro',
    category: 'box',
    description: 'Movie Fragment Random Access Offset Box. Stores the size of the mfra box.',
    whyItMatters: 'Because mfra is usually near the end of the file, mfro helps readers locate the start of mfra by reading from the end.',
  },
  {
    id: 'traf',
    label: 'traf',
    category: 'fragmented-mp4',
    description: 'Track Fragment Box. Holds fragment metadata for one track.',
    whyItMatters: 'Fragments can carry multiple tracks, each with its own traf metadata.',
  },
  {
    id: 'tfhd',
    label: 'tfhd',
    category: 'fragmented-mp4',
    description: 'Track Fragment Header Box. Identifies the track and provides defaults.',
    whyItMatters: 'Default sample values reduce repetition and tell the player which track the fragment belongs to.',
  },
  {
    id: 'tfdt',
    label: 'tfdt',
    category: 'timing',
    description: 'Track Fragment Decode Time Box. Gives the base decode time for the fragment.',
    whyItMatters: 'It places a fragment on the media timeline for smooth playback and ABR alignment.',
  },
  {
    id: 'trun',
    label: 'trun',
    category: 'sample-table',
    description: 'Track Run Box. Describes samples inside a media fragment.',
    whyItMatters: 'Acts like a mini sample table for a segment, listing sample sizes, durations, and flags.',
  },
]

export const edges: Edge[] = [
  { source: 'mp4-file', target: 'progressive-mp4', label: 'can be', description: 'An MP4 file can be authored as a progressive MP4 for single-file playback.' },
  { source: 'mp4-file', target: 'fragmented-mp4', label: 'can be', description: 'An MP4 file can be fragmented for streaming and incremental playback.' },
  { source: 'progressive-mp4', target: 'ftyp', label: 'contains', description: 'A progressive MP4 contains an ftyp box declaring compatible brands.' },
  { source: 'progressive-mp4', target: 'moov', label: 'contains', description: 'A progressive MP4 contains a moov box with global metadata and sample tables.' },
  { source: 'progressive-mp4', target: 'mdat', label: 'contains', description: 'A progressive MP4 contains mdat bytes for the encoded media payload.' },
  { source: 'fragmented-mp4', target: 'init-segment', label: 'uses', description: 'A fragmented MP4 begins with an init segment that declares the media structure.' },
  { source: 'fragmented-mp4', target: 'media-segment', label: 'uses', description: 'A fragmented MP4 continues as media segments, each carrying fragment metadata and payload.' },
  { source: 'init-segment', target: 'ftyp', label: 'contains', description: 'An init segment contains the ftyp box, which identifies compatible ISOBMFF brands.' },
  { source: 'init-segment', target: 'moov', label: 'contains', description: 'An init segment contains the moov box, which provides global track and codec metadata.' },
  { source: 'media-segment', target: 'styp', label: 'may contain', description: 'A media segment may contain styp to declare segment-level compatibility brands.' },
  { source: 'media-segment', target: 'sidx', label: 'may contain', description: 'A media segment may contain optional sidx indexing metadata.' },
  { source: 'media-segment', target: 'moof', label: 'contains', description: 'A fragmented MP4 media segment contains a moof box describing the samples in that segment.' },
  { source: 'media-segment', target: 'mdat', label: 'contains', description: 'A fragmented MP4 media segment contains mdat bytes for the samples described by moof.' },
  { source: 'fragmented-mp4', target: 'mfra', label: 'may contain', description: 'A fragmented MP4 may include an mfra box, commonly near the end, to support random access.' },
  { source: 'mfra', target: 'tfra', label: 'contains', description: 'mfra can contain tfra boxes with track-specific random-access entries.' },
  { source: 'mfra', target: 'mfro', label: 'contains', description: 'mfra ends with mfro, which records the mfra box size.' },
  { source: 'media-fragment', target: 'media-segment', label: 'behind', description: 'A media fragment is the container-level structure behind fMP4 media segments.' },
  { source: 'media-fragment', target: 'moof', label: 'uses', description: 'A media fragment uses moof metadata to describe its track runs.' },
  { source: 'media-fragment', target: 'mdat', label: 'uses', description: 'A media fragment pairs metadata with mdat payload bytes.' },
  { source: 'mfra', target: 'media-fragment', label: 'indexes', description: 'mfra indexes random-access positions inside movie fragments.' },
  { source: 'mfra', target: 'moof', label: 'points to', description: 'mfra entries can point to moof byte offsets for fast fragment lookup.' },
  { source: 'moov', target: 'mvhd', label: 'contains', description: 'The moov box contains mvhd for movie-level timing and presentation metadata.' },
  { source: 'moov', target: 'mvex', label: 'may contain', description: 'A fragmented MP4 moov contains mvex to define movie fragment defaults.' },
  { source: 'mvex', target: 'trex', label: 'contains', description: 'mvex contains trex boxes that define per-track fragment defaults.' },
  { source: 'moov', target: 'trak', label: 'contains', description: 'The moov box contains one or more trak boxes, one for each track.' },
  { source: 'trak', target: 'tkhd', label: 'contains', description: 'A trak contains tkhd for track identity and display/header properties.' },
  { source: 'trak', target: 'mdia', label: 'contains', description: 'A trak contains mdia, which holds media-specific track information.' },
  { source: 'mdia', target: 'minf', label: 'contains', description: 'The mdia box contains minf, grouping media information for the track.' },
  { source: 'minf', target: 'stbl', label: 'contains', description: 'The minf box contains stbl, the sample table for locating and timing samples.' },
  { source: 'stbl', target: 'stsd', label: 'contains', description: 'The sample table contains stsd for codec and sample entry descriptions.' },
  { source: 'stsd', target: 'av1c', label: 'may reference', description: 'AV1 sample descriptions use av1C for codec initialization data.' },
  { source: 'stsd', target: 'avcc', label: 'may reference', description: 'H.264 sample descriptions use avcC for codec initialization data.' },
  { source: 'stsd', target: 'hvcc', label: 'may reference', description: 'HEVC sample descriptions use hvcC for codec initialization data.' },
  { source: 'stsd', target: 'esds', label: 'may reference', description: 'Some MPEG-4 sample descriptions use esds for elementary stream decoder configuration.' },
  { source: 'stbl', target: 'stts', label: 'contains', description: 'The sample table contains stts to map samples to decode durations.' },
  { source: 'stbl', target: 'stss', label: 'contains', description: 'The sample table contains stss to identify keyframes or sync samples.' },
  { source: 'stbl', target: 'stsz', label: 'contains', description: 'The sample table contains stsz to identify sample sizes.' },
  { source: 'stbl', target: 'stco-co64', label: 'contains', description: 'The sample table contains stco or co64 to map chunks to byte offsets.' },
  { source: 'mdat', target: 'stco-co64', label: 'located by', description: 'mdat contains encoded bytes that chunk offset boxes point into.' },
  { source: 'moof', target: 'traf', label: 'contains', description: "A moof contains one or more traf boxes, each describing one track's fragment metadata." },
  { source: 'traf', target: 'tfhd', label: 'contains', description: 'traf contains tfhd, which identifies the track and provides default sample values.' },
  { source: 'traf', target: 'tfdt', label: 'contains', description: 'traf contains tfdt, which gives the base decode time for the fragment.' },
  { source: 'traf', target: 'trun', label: 'contains', description: 'traf contains trun, which describes the samples inside the fragment.' },
  { source: 'tfhd', target: 'trun', label: 'defaults for', description: 'tfhd values are defaults that trun entries can use or override.' },
  { source: 'tfdt', target: 'trun', label: 'times', description: 'tfdt anchors the decode timeline for the samples described by trun.' },
  { source: 'abr', target: 'manifest', label: 'uses', description: 'ABR uses a manifest to discover available representations and segment URLs.' },
  { source: 'manifest', target: 'representation', label: 'lists', description: 'A manifest lists representations such as bitrate and resolution variants.' },
  { source: 'representation', target: 'init-segment', label: 'has', description: 'Each representation has its own init segment with compatible metadata for that variant.' },
  { source: 'representation', target: 'media-segment', label: 'has', description: 'Each representation has its own media segments for each time range.' },
  { source: 'abr', target: 'representation', label: 'switches', description: 'ABR switches between time-aligned representations to adapt quality without changing playback time.' },
]
